[package]
name = "add-ntp-default-options-v0-1-0"
version = "0.1.0"
authors = ["Dom Goodwin <domgoodwin@monzo.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
migration-helpers = { path = "../../../migration-helpers", version = "0.1.0"}
